### ISSUE TITLE
Installation doesn't work....

### ISSUE THREAD

**Issue by varmint09** [angulartics/angulartics-google-analytics#1]
Hopefully I am not doing something stupid but... also not sure why you bother creating an _index.js to load and export a file, when you could just wrap the file in those? Either way its failing to load. 

require('angulartics-google-analytics');

var requires = [
    '...',
    'angulartics.google.analytics',
    ...',
  ];

Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module angulartics.google.analytics due to:
Error: [$injector:modulerr] Failed to instantiate module angulartics due to:
Error: [$injector:nomod] Module 'angulartics' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Many thanks

**Comment by luisfarzati** [comment]
Sorry, I've improved the docs now. This is a plugin, so I was assuming Angulartics was already installed, but I clarified this in the README now.

```js
require('angulartics')

angular.module('myApp', [
  'angulartics', 
  require('angulartics-google-analytics')
])
```

This is the complete example. Pretty soon we'll move Angulartics to the new org as well, and you will be able to do

```js
angular.module('myApp', [
  require('angulartics'), 
  require('angulartics-google-analytics')
])
```

**Comment by luisfarzati** [comment]
Regarding your first question about the `index.js`, I liked the way Angular implemented this for their own packages ([angular-resource](https://github.com/angular/bower-angular-resource), [angular-cookies](https://github.com/angular/bower-angular-cookies), etc). One file is for bower, and the other provides a simple thin wrapper for npm.

**Comment by varmint09** [comment]
Makes sense, but as angulartics isn't on npm, I can't use the submodule from it either, as bower introduces angular which conflicts with my npm install of angukar.

Guess I'll need to wait for the angulartics to hit npm too.

Many thanks and best of luck.

**Comment by luisfarzati** [comment]
Sorry, I'm not sure what you mean. 

```shell
npm install angulartics
```

is not working for you?

It is published on npm, and you can use it as in my example above.

The entire setup should be:

```bash
npm i angular angulartics angulartics-google-analytics
```

then in your js file:

```js
var angular = require('angular')
require('angulartics') // until we package it as a CommonJS module

angular.module('myApp', ['angulartics', require('angulartics-google-analytics')])
```

or to make it clearer:

```js
var angular = require('angular')
require('angulartics') // until we package it as a CommonJS module
var googleanalytics = require('angulartics-google-analytics')

angular.module('myApp', ['angulartics', googleanalytics])
```

**Comment by luisfarzati** [comment]
What I meant with properly packaging angulartics for npm was that it will follow the "Angular way" to export the name of the module (as happens today with the official angular modules resource, cookies, etc.). But the current package works fine if you just `require` it.

**Comment by varmint09** [comment]
Hi, yes after the clarification this all works now.

Awesome stuff.

**Comment by luisfarzati** [comment]
:+1:

**Comment by sinedied** [comment]
Strange, I have this issue on Safari, while the same code works on Chrome... 

```
Error: [$injector:modulerr] Failed to instantiate module app due to:
[$injector:modulerr] Failed to instantiate module angulartics.google.analytics due to:
[$injector:nomod] Module 'angulartics.google.analytics' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

I have the modules declared correctly in my app:
```
export default angular.module('app', [
  'translations',
  'gettext',
  'ngAnimate',
  'ngSanitize',
  'ngCordova',
  'ui.router',
  'ionic',
  'angulartics',
  'angulartics.google.analytics',
  'ion-affix',
  'uiGmapgoogle-maps',
  'ngYoutubeEmbed',
  'plangular'
]);
```

Any ideas?

**Comment by sinedied** [comment]
Found the issue: adblock plus on safari simply block the execution of the module code :(
The same code works though on Chrome/Firefox with the adblock plus extension, strange :/

**Comment by SangeetAgarwal** [comment]
`
Error: [$injector:modulerr] Failed to instantiate module Repcard due to:
[$injector:modulerr] Failed to instantiate module angulartics.google.analytics due to:
[$injector:nomod] Module 'angulartics.google.analytics' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.10/$injector/nomod?p0=angulartics.google.analytics
minErr/<@http://localhost:9001/vendor/js/angular/angular.js:68:12
module/<@http://localhost:9001/vendor/js/angular/angular.js:2129:17
ensure@http://localhost:9001/vendor/js/angular/angular.js:2053:38
module@http://localhost:9001/vendor/js/angular/angular.js:2127:14
loadModules/<@http://localhost:9001/vendor/js/angular/angular.js:4665:22
forEach@http://localhost:9001/vendor/js/angular/angular.js:325:11
loadModules@http://localhost:9001/vendor/js/angular/angular.js:4649:5
loadModules/<@http://localhost:9001/vendor/js/angular/angular.js:4666:40
forEach@http://localhost:9001/vendor/js/angular/angular.js:325:11
loadModules@http://localhost:9001/vendor/js/angular/angular.js:4649:5
createInjector@http://localhost:9001/vendor/js/angular/angular.js:4571:19
bootstrap/doBootstrap@http://localhost:9001/vendor/js/angular/angular.js:1805:20
bootstrap@http://localhost:9001/vendor/js/angular/angular.js:1826:12
angularInit@http://localhost:9001/vendor/js/angular/angular.js:1711:5
@http://localhost:9001/vendor/js/angular/angular.js:32539:5
jQuery.Callbacks/fire@http://localhost:9001/vendor/js/jquery/jquery.js:3187:11
jQuery.Callbacks/self.fireWith@http://localhost:9001/vendor/js/jquery/jquery.js:3317:7
.ready@http://localhost:9001/vendor/js/jquery/jquery.js:3536:3
completed@http://localhost:9001/vendor/js/jquery/jquery.js:3552:2

http://errors.angularjs.org/1.5.10/$injector/modulerr?p0=angulartics.google.analytics&p1=%5B%24injector%3Anomod%5D%20Module%20'angulartics.google.analytics'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fnomod%3Fp0%3Dangulartics.google.analytics%0AminErr%2F%3C%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A68%3A12%0Amodule%2F%3C%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A2129%3A17%0Aensure%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A2053%3A38%0Amodule%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A2127%3A14%0AloadModules%2F%3C%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4665%3A22%0AforEach%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A325%3A11%0AloadModules%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4649%3A5%0AloadModules%2F%3C%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4666%3A40%0AforEach%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A325%3A11%0AloadModules%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4649%3A5%0AcreateInjector%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4571%3A19%0Abootstrap%2FdoBootstrap%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A1805%3A20%0Abootstrap%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A1826%3A12%0AangularInit%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A1711%3A5%0A%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A32539%3A5%0AjQuery.Callbacks%2Ffire%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3187%3A11%0AjQuery.Callbacks%2Fself.fireWith%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3317%3A7%0A.ready%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3536%3A3%0Acompleted%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3552%3A2%0A
minErr/<@http://localhost:9001/vendor/js/angular/angular.js:68:12
loadModules/<@http://localhost:9001/vendor/js/angular/angular.js:4688:15
forEach@http://localhost:9001/vendor/js/angular/angular.js:325:11
loadModules@http://localhost:9001/vendor/js/angular/angular.js:4649:5
loadModules/<@http://localhost:9001/vendor/js/angular/angular.js:4666:40
forEach@http://localhost:9001/vendor/js/angular/angular.js:325:11
loadModules@http://localhost:9001/vendor/js/angular/angular.js:4649:5
createInjector@http://localhost:9001/vendor/js/angular/angular.js:4571:19
bootstrap/doBootstrap@http://localhost:9001/vendor/js/angular/angular.js:1805:20
bootstrap@http://localhost:9001/vendor/js/angular/angular.js:1826:12
angularInit@http://localhost:9001/vendor/js/angular/angular.js:1711:5
@http://localhost:9001/vendor/js/angular/angular.js:32539:5
jQuery.Callbacks/fire@http://localhost:9001/vendor/js/jquery/jquery.js:3187:11
jQuery.Callbacks/self.fireWith@http://localhost:9001/vendor/js/jquery/jquery.js:3317:7
.ready@http://localhost:9001/vendor/js/jquery/jquery.js:3536:3
completed@http://localhost:9001/vendor/js/jquery/jquery.js:3552:2

http://errors.angularjs.org/1.5.10/$injector/modulerr?p0=ncqaReportCards&p1=%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20angulartics.google.analytics%20due%20to%3A%0A%5B%24injector%3Anomod%5D%20Module%20'angulartics.google.analytics'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fnomod%3Fp0%3Dangulartics.google.analytics%0AminErr%2F%3C%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A68%3A12%0Amodule%2F%3C%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A2129%3A17%0Aensure%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A2053%3A38%0Amodule%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A2127%3A14%0AloadModules%2F%3C%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4665%3A22%0AforEach%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A325%3A11%0AloadModules%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4649%3A5%0AloadModules%2F%3C%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4666%3A40%0AforEach%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A325%3A11%0AloadModules%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4649%3A5%0AcreateInjector%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4571%3A19%0Abootstrap%2FdoBootstrap%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A1805%3A20%0Abootstrap%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A1826%3A12%0AangularInit%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A1711%3A5%0A%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A32539%3A5%0AjQuery.Callbacks%2Ffire%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3187%3A11%0AjQuery.Callbacks%2Fself.fireWith%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3317%3A7%0A.ready%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3536%3A3%0Acompleted%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3552%3A2%0A%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fmodulerr%3Fp0%3Dangulartics.google.analytics%26p1%3D%255B%2524injector%253Anomod%255D%2520Module%2520'angulartics.google.analytics'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.10%252F%2524injector%252Fnomod%253Fp0%253Dangulartics.google.analytics%250AminErr%252F%253C%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A68%253A12%250Amodule%252F%253C%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A2129%253A17%250Aensure%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A2053%253A38%250Amodule%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A2127%253A14%250AloadModules%252F%253C%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A4665%253A22%250AforEach%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A325%253A11%250AloadModules%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A4649%253A5%250AloadModules%252F%253C%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A4666%253A40%250AforEach%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A325%253A11%250AloadModules%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A4649%253A5%250AcreateInjector%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A4571%253A19%250Abootstrap%252FdoBootstrap%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A1805%253A20%250Abootstrap%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A1826%253A12%250AangularInit%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A1711%253A5%250A%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fangular%252Fangular.js%253A32539%253A5%250AjQuery.Callbacks%252Ffire%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fjquery%252Fjquery.js%253A3187%253A11%250AjQuery.Callbacks%252Fself.fireWith%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fjquery%252Fjquery.js%253A3317%253A7%250A.ready%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fjquery%252Fjquery.js%253A3536%253A3%250Acompleted%2540http%253A%252F%252Flocalhost%253A9001%252Fvendor%252Fjs%252Fjquery%252Fjquery.js%253A3552%253A2%250A%0AminErr%2F%3C%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A68%3A12%0AloadModules%2F%3C%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4688%3A15%0AforEach%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A325%3A11%0AloadModules%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4649%3A5%0AloadModules%2F%3C%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4666%3A40%0AforEach%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A325%3A11%0AloadModules%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4649%3A5%0AcreateInjector%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A4571%3A19%0Abootstrap%2FdoBootstrap%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A1805%3A20%0Abootstrap%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A1826%3A12%0AangularInit%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A1711%3A5%0A%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fangular%2Fangular.js%3A32539%3A5%0AjQuery.Callbacks%2Ffire%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3187%3A11%0AjQuery.Callbacks%2Fself.fireWith%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3317%3A7%0A.ready%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3536%3A3%0Acompleted%40http%3A%2F%2Flocalhost%3A9001%2Fvendor%2Fjs%2Fjquery%2Fjquery.js%3A3552%3A2%0A
	

angular.js (line 68, col 12)
`

similar issue as @sinedied - happens with ublock origin on firefox. Is there a fix for this?

**Comment by mjrdnk** [comment]
Same issue here. Is there a way to lazy-load angulartics modules in AngularJS app? When ad-block is used on the client, it causes JS error and no page is displayed. Has anyone walked it around already?
Thanks!

**Comment by mjrdnk** [comment]
There is actually no issue anymore, as the module fails to load locally on development setup via bower. It works on prod though! No issue

**Comment by SangeetAgarwal** [comment]
@mjrdnk can you share how you got it to work on prod with ad-block on client?

**Comment by mjrdnk** [comment]
@SangeetAgarwal Well, what I mean by 'it works', is it does not cause javascript error and the app is still functional. Tracking is disabled though. On prod we serve minified vendor and our own code.On dev env it just caused [...modulerr] error typical to misspealing module name in app.module.js.

**Comment by timelf123** [comment]
summary: bundle your angulartics code (app.js) or rename the files to avoid adblock

**Comment by SangeetAgarwal** [comment]
doesn't seem to work, so
` (function (i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function () {
          (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
      a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'some-key', 'auto');
    ga('send', 'pageview');`

and, put in a usageTracker.js file which i then refer to in my index.html

I also put the above code in the app.js. The app.js is minified. Even then with (say) ublock on firefox the site does not render. @timelf123 what might i be missing? thanks

**Comment by mjrdnk** [comment]
@SangeetAgarwal could you provide your how you load your vendor components in html? Are you using any building solution like bower?
You should be serving all vendor resources, as well as your app bundled together using bower, webpack or similar tool.
Correct me if I am wrong. Cheers!

**Comment by SangeetAgarwal** [comment]
@mjrdnk I'm using `grunt-contrib-uglify` for minifying vendor components and `grunt-ng-annotate` . Here's snippet of how I inject angulartics
`var app=angular.module("ncqaReportCards",["ngRoute","ngSanitize","ngCookies","ui.router","bw.paging","config","angulartics","angulartics.google.analytics","ngMap","angular-loading-bar"]);app.config(["$urlRouterProvider","$stateProvider","$logProvider","cfpLoadingBarProvider",function`

In the html 
`    <script type="text/javascript" src="vendor/js/angulartics-google-analytics/angulartics-ga.js"></script>
    <script type="text/javascript" src="vendor/js/angulartics/angulartics.js"></script>
   <script type="text/javascript" src="js/trackUsage.js"></script>`

contents of trackUsage
`!function(a,b,c,d,e,f,g){a.GoogleAnalyticsObject=e,a[e]=a[e]||function(){(a[e].q=a[e].q||[]).push(arguments)},a[e].l=1*new Date,f=b.createElement(c),g=b.getElementsByTagName(c)[0],f.async=1,f.src=d,g.parentNode.insertBefore(f,g)}(window,document,"script","https://www.google-analytics.com/analytics.js","ga"),ga("create","some-UA","auto"),ga("send","pageview");
`

I'm using grunt as the task runner and bower

**Comment by timelf123** [comment]
Bundle these three files into one renamed file:

```
<script type="text/javascript" src="vendor/js/angulartics-google-analytics/angulartics-ga.js"></script>
    <script type="text/javascript" src="vendor/js/angulartics/angulartics.js"></script>
   <script type="text/javascript" src="js/trackUsage.js"></script>
```

```
<script type="text/javascript" src="app.js"></script>
```

**Comment by SangeetAgarwal** [comment]
@timelf123 - awesome! - that works - thanks
