### ISSUE TITLE
bower.json dependencies point to old version of angulartics (1.8.0)

### ISSUE THREAD

**Issue by seadour** [angulartics/angulartics-google-analytics#3]
https://github.com/angulartics/angulartics-google-analytics/blob/master/bower.json

    {
      "name": "angulartics-google-analytics",
      "main": "./dist/angulartics-google-analytics.min.js",
      "dependencies": {
        "angulartics": "~0.18.0"
      },
      "ignore": [
        "**/.*",
        "bower_components",
        "node_modules",
        "example",
        "package.json",
        "lib/index.js"
      ]
    }

**Comment by lunks** [comment]
I'll be releasing new versions for angulartics plugins depending on 0.20.0 later today.

**Comment by seadour** [comment]
Thanks @lunks!

**Comment by kentcdodds** [comment]
Could you make sure to do the same for `npm` in the `package.json`?

**Comment by kentcdodds** [comment]
Note, for `npm`, a more appropriate field to add the dependency would be in the `peerDependencies` (and remove it from `dependencies` entirely).

**Comment by lunks** [comment]
@kentcdodds could you please elaborate why `angulartics` would be a peer dependency instead of a dependency? IMHO it should be a dependency as we require `angulartics` in order for the plugin to work.

**Comment by kentcdodds** [comment]
The reason I don't want it as a `dependency` is because when I `npm install angulartics-google-analytics` it installs `angulartics` as a `node_module` inside itself like so:

```
~/Desktop
🐑  $ npm install angulartics-google-analytics
angulartics-google-analytics@0.1.1 node_modules/angulartics-google-analytics
└── angulartics@0.20.0
~/Desktop
🐑  $ 
```

This actually turns out to not be a huge problem because you don't actually require angulartics anywhere in your code. However, if you decide to upgrade to ES6 with webpack or browserify, when you start doing this, you'll be requiring your own `angulartics` package rather than mine. This is bad because not only would I be loading two versions of `angulartics` (one for your library plugin and one for my app) but it could also be that I have a newer version of `angulartics`. So having [very loose requirements](http://semver.npmjs.com/) for `peerDependencies` is a good idea because npm will ensure that I have my own copy installed, but it wont install a local copy for your lib. (Note, you should do this for `angular` as well).

I should note also that if you ever do upgrade to webpack, you'll want to use the `externals` feature for both `angular` and `angulartics`. I'm sure browserify has something like this as well.

I hope that makes sense! I do this with several of my libraries ([angular-formly](https://github.com/formly-js/angular-formly/blob/master/package.json#L79-L82) included) and it's proven to be highly effective.

**Comment by luisfarzati** [comment]
Yeap, that makes sense.

**Comment by timelf123** [comment]
Fixed by https://github.com/angulartics/angulartics-google-analytics/commit/26b3f23d928b5a34a765a348eabd3edd0487a0f2

Thanks @kentcdodds for the direction
