### ISSUE TITLE
Multiple tracking codes with google analytics

### ISSUE THREAD

**Issue by asendro** [angulartics/angulartics-google-analytics#59]

**Comment by CurlyBraceTT** [comment]
Why its closed?

**Comment by timelf123** [comment]
$analyticsProvider.settings.ga.additionalAccountNames = ['ua-123', 'ua-456']

**Comment by CurlyBraceTT** [comment]
Thanks. I was just using outdated Nuget version, noticed it days after.

**Comment by timelf123** [comment]
No problem, glad you have it sorted out

**Comment by TaylorAckley** [comment]
@timelf123 In your example, those are ADDITIONAL GA codes and not the first code + an additional code, correct?   If I only have one additional code, I would not set it to dictionary, but a string with the single additional code, correct?

In my case, I am setting the tracking codes create action as normal:

`ga('create', 'UA-402xxx-1', 'auto');
ga('create', 'UA-4027xxxx-4', 'auto',{'name':'xxx'});`

then in:

`$analyticsProvider.settings.ga.additionalAccountNames = `UA-4027xxxx-4``

I am not setting the first code, because its not an 'additional code' and covered by the normal send/pageview action.    Does that sound correct, or should I add both codes as a dictionary?

Any guidance would be appreciated.

**Comment by DanWilkerson** [comment]
@TaylorAckley Try setting `$analyticsProvider.settings.ga.additionalAccountName = ['xxx'];`. That setting should be an array of strings, where each string is the `{name: NAME}` configuration set when issuing the create command.

**Comment by bennyt2** [comment]
I had some trouble implementing multiple accounts, so here's how I did it. Note: I am using analytics.js.

Step 1: Call ga.create() for each account you intend to send to. You must define the 4th argument, a name, for every tracker after the first one

```javascript
ga('create', 'UA-710xxxx-1', 'auto');
ga('create', 'UA-711xxxx-3', 'auto', 'tracker2');
ga('create', 'UA-712xxxx-5', 'auto', 'tracker3');
```

Step 2: In your .config function, add the **names** of each additional tracker, not the IDs, to the `$analyticsProvider.settings.ga.additionalAccountNames` array. This is where I got confused. At first, I was trying to add the GA ID without calling ga.create(). That didn't work. Then, I tried to use the GA ID as the name. That didn't work either. Once I used a string like 'tracker2' as a name, then it worked.

```javascript
...
    .config([
        '$analyticsProvider',
        function ($analyticsProvider) {
            $analyticsProvider.settings.ga.additionalAccountNames = ['tracker2','tracker3'];
        }
    ]);
...
```

Multiple trackers should now be working properly.

See [the docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers) for reference.
