### ISSUE TITLE
Cross-domain support?

### ISSUE THREAD

**Issue by chrissom** [angulartics/angulartics-google-analytics#66]
Hi,

Nice job! Does the cross-domain is supported?

**Comment by DanWilkerson** [comment]
Hi Chrissom,

You'll need to configure this with you Analytics snippet at the moment. Here's the docs to get you started:

https://developers.google.com/analytics/devguides/collection/analyticsjs/cross-domain

Once you've updated the basic configuration of your tracker, you shouldn't need to do anything to angulartics and everything _should_ play nicely. Let me know if otherwise. Closing for now!
